# Set environment variables.
environment:
  PYTHON: C:/Python27-x64

  # We bundle up protoc.exe and only the parts of boost and openssl we need so
  # that it's a small download. We also use appveyor's free cache, avoiding fees
  # downloading from S3 each time.
  # TODO: script to create this package.
  JBCOIND_DEPS_URL: https://jbcoin.github.io/Downloads/appveyor/jbcoind_deps15.01.zip

  # Other dependencies we just download each time.
  PIP_URL: https://bootstrap.pypa.io/get-pip.py
  PYWIN32_URL: https://downloads.sourceforge.net/project/pywin32/pywin32/Build%20220/pywin32-220.win-amd64-py2.7.exe

  # Scons honours these environment variables, setting the include/lib paths.
  BOOST_ROOT: C:/jbcoind_deps15.01/boost
  OPENSSL_ROOT: C:/jbcoind_deps15.01/openssl

  matrix:
  - build: cmake
    target: msvc.debug
    app: jbcoinlibppdemo

os: Visual Studio 2015

# At the end of each successful build we cache this directory. It must be less
# than 100MB total compressed.
cache:
  - "C:\\jbcoind_deps15.01"

# Only clone the last 20 commits.
clone_depth: 20

install:
  # Grab submodules
  - git submodule update --init --recursive
  # We want easy_install, python and protoc.exe on PATH.
  - SET PATH=%PYTHON%;%PYTHON%/Scripts;C:/jbcoind_deps15.01;%PATH%

  # `ps` prefix means the command is executed by powershell.
  - ps: |
        if ($env:build -eq "scons") {
          Start-FileDownload $env:PIP_URL
          Start-FileDownload $env:PYWIN32_URL

          & extras/jbcoind/bin/ci/windows/install-dependencies.bat
        }

  # Download dependencies if appveyor didn't restore them from the cache.
  # Use 7zip to unzip.
  - ps: |
        if (-not(Test-Path 'C:/jbcoind_deps15.01')) {
            echo "Download from $env:JBCOIND_DEPS_URL"
            Start-FileDownload "$env:JBCOIND_DEPS_URL"
            7z x jbcoind_deps15.01.zip -oC:\ -y > $null
        }

  # Newer DEPS include a versions file.
  # Dump it so we can verify correct behavior.
  - ps: |
        if (Test-Path 'C:/jbcoind_deps15.01/versions.txt') {
          cat 'C:/jbcoind_deps15.01/versions.txt'
        }

# TODO: This is giving me grief
# artifacts:
#   # Save jbcoind.exe in the cloud after each build.
#   - path: "build\\jbcoind.exe"

build_script:
  # We set the environment variables needed to put compilers on the PATH.
  - '"%VS140COMNTOOLS%../../VC/vcvarsall.bat" x86_amd64'
  # Show which version of the compiler we are using.
  - cl
  - ps: |
        if ($env:build -eq "scons") {
          # Build with scons
          scons $env:target -j%NUMBER_OF_PROCESSORS%
        }
        else
        {
          # Build with cmake
          cmake --version
          $cmake_target="$($env:target).ci"
          "$cmake_target"
          New-Item -ItemType Directory -Force -Path "build/$cmake_target"
          Push-Location "build/$cmake_target"
          cmake -G"Visual Studio 14 2015 Win64" -Dtarget="$cmake_target" ../..
          cmake --build . -- -m
          Pop-Location
        }

after_build:
  - ps: |
        if ($env:build -eq "scons") {
          # Put our executable in a place where npm test can find it.
          cp build/$($env:target)/jbcoind.exe build
          ls build
          $exe="build/$env:app"
        }
        else
        {
          $exe="build/$cmake_target/Debug/$env:app"
        }
        "Exe is at $exe"

test_script:
  - ps: |
        if (-NOT (Test-Path env:\app) -or ($env::app -eq "jbcoind")) {
          # Run the jbcoind unit tests
          & $exe --unittest

          # Run the jbcoind integration tests
          & npm install --progress=false
          & npm test --jbcoind="$exe"
        }
        else
        {
          # Just run the app
          & $exe
        }


